#Requires AutoHotkey v2.0

global CONFIG_FILE_EXTENSION := ".config"
global STRING_EMPTY := ""
global UNKNOWN := "<unknown>"

global SECOND_IN_MILLISECONDS := 1000
global MINUTE_IN_MILLISECONDS := 60 * SECOND_IN_MILLISECONDS
global HOUR_IN_MILLISECONDS := 60 * MINUTE_IN_MILLISECONDS

global DEFAULT_SPACES_PER_INDENT := 4